---
# This playbook contains common plays that will be run on all nodes.

- name: Install Python Scripts
  apt: name={{ item }} state=installed
  with_items:
   - autoconf 
   - automake 
   - build-essential 
   - libass-dev 
   - libfreetype6-dev 
   - libgpac-dev 
   - libsdl1.2-dev 
   - libtheora-dev 
   - libtool 
   - libva-dev 
   - libvdpau-dev 
   - libvorbis-dev 
   - libx11-dev 
   - libxext-dev 
   - libxfixes-dev 
   - pkg-config 
   - texi2html 
   - zlib1g-dev
   - libfaac-dev
   - libpcre3-dev
   - gcc
   - libssl-dev
  sudo: yes
